import { Fragment } from "react";
import Head from "next/head";

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Audiophile E-Commmerce App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        <h1 className="title">Hello</h1>
      </div>
    </Fragment>
  );
}
